// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("ticket")]
	public class Ticket
	{
		[Column("id", IsPrimaryKey = true)] public Guid Id { get; set; } // uuid
		[Column("generated_time")] public DateTimeOffset? GeneratedTime { get; set; } // timestamp (6) with time zone
		[Column("vatin")] public string? Vatin { get; set; } // character(11)
		[Column("first_name")] public string? FirstName { get; set; } // character varying(64)
		[Column("last_name")] public string? LastName { get; set; } // character varying(64)
	}
}
